swagger: "2.0"
info:
    title: Bank Argent API documentation
    description: Contient toute la documentation de l'API du frontend de Bank Argent
    version: "1.0.0"
    termsOfService: "http://swagger.io/terms/"
host: "localhost:3001"
basePath: "/api/v1"
schemes:
    - "http"
paths:
    /user/login:
        post:
            tags:
                - User Module
            summary: Login
            description: API for Login
            parameters:
                - in: body
                  name: body
                  description: Login Payload
                  required: true
                  schema:
                      $ref: "#/definitions/Login"
            produces:
                - application/json
            responses:
                "200":
                    description: Login Successfully
                    schema:
                        $ref: "#/definitions/LoginResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/signup:
        post:
            tags:
                - User Module
            summary: Signup
            description: API for Signup
            parameters:
                - in: body
                  name: body
                  description: Signup Payload
                  required: true
                  schema:
                      $ref: "#/definitions/User"
            produces:
                - application/json
            responses:
                "200":
                    description: Signup Successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "400":
                    description: Invalid Fields
                "500":
                    description: Internal Server Error
    /user/profile:
        get:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for fetching a user profile
            responses:
                "200":
                    description: User profile retrieved successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
        put:
            security:
                - Bearer: []
            tags:
                - User Module
            summary: User Profile API
            description: API for updating a user profile
            parameters:
                - in: body
                  name: body
                  description: Update user profile attributes
                  required: true
                  schema:
                      $ref: "#/definitions/UserProfile"
            produces:
                - application/json
            responses:
                "200":
                    description: User profile updated successfully
                    schema:
                        $ref: "#/definitions/ApiResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Get all transactions
            description: Récupère toutes les transactions d'un utilisateur connecté
            produces:
                - application/json
            responses:
                "200":
                    description: OK
                    schema:
                        type: array
                        items:
                            type: object
                            properties:
                                id:
                                    type: string
                                    example: "tx123"
                                amount:
                                    type: number
                                    example: 50.00
                                description:
                                    type: string
                                    example: "Grocery Shopping"
                                date:
                                    type: string
                                    example: "2024-10-21"
                                balance:
                                    type: number
                                    example: 950.50
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction/{id}:
        get:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Get transaction information
            description: Récupère les informations d'une transaction d'un utilisateur connecté
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: OK
                    schema:
                        type: object
                        properties:
                            id:
                                type: string
                                example: "tx123"
                            amount:
                                type: number
                                example: 50.00
                            description:
                                type: string
                                example: "Grocery Shopping"
                            date:
                                type: string
                                example: "2024-10-21"
                            balance:
                                type: number
                                example: 950.50
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction/category/{id}:
        put:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Update transaction category
            description: Met à jour la catégorie d'une transaction existante
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Payload to update category
                  required: true
                  schema:
                      type: object
                      properties:
                          category:
                              type: string
                              example: "Groceries"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction category updated successfully
                    schema:
                        $ref: "#/definitions/UpdateResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
        delete:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Delete transaction category
            description: Supprime la catégorie d'une transaction
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction category deleted successfully
                    schema:
                        $ref: "#/definitions/UpdateResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
    /transaction/note/{id}:
        put:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Update transaction note
            description: Met à jour la note d'une transaction existante
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
                - in: body
                  name: body
                  description: Payload to update note
                  required: true
                  schema:
                      type: object
                      properties:
                          note:
                              type: string
                              example: "Bought fruits and vegetables"
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction note updated successfully
                    schema:
                        $ref: "#/definitions/UpdateResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
        delete:
            security:
                - Bearer: []
            tags:
                - Transaction
            summary: Delete transaction note
            description: Supprime la note d'une transaction
            parameters:
                - name: id
                  in: path
                  required: true
                  type: string
            produces:
                - application/json
            responses:
                "200":
                    description: Transaction note deleted successfully
                    schema:
                        $ref: "#/definitions/UpdateResponse"
                "401":
                    description: Unauthorized
                "500":
                    description: Internal Server Error
securityDefinitions:
    Bearer:
        type: apiKey
        name: Authorization
        in: header
definitions:
    User:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
            firstName:
                type: string
                description: user first name
            lastName:
                type: string
                description: user last name
            userName:
                type: string
                description: user public name
    Login:
        properties:
            email:
                type: string
                description: user email
            password:
                type: string
                description: user password
    ApiResponse:
        type: object
        properties:
            status:
                type: integer
            message:
                type: string
            body:
                type: object
                properties:
                    id:
                        type: string
                    email:
                        type: string
    LoginResponse:
        type: object
        properties:
            token:
                type: string
    UserProfile:
        type: object
        properties:
            userName:
                type: string
            firstName:
                type: string
            lastName:
                type: string
            email:
                type: string
    UpdateResponse:
        type: object
        properties:
            status:
                type: integer
                example: 200
            message:
                type: string
                example: "Transaction updated successfully"
            body:
                type: object
                properties:
                    id:
                        type: string
                    category:
                        type: string
                    note:
                        type: string
